import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-natural-gas-imbalance-pipeline-settlement",
  "engine": "recovery",
  "title": "Natural Gas Imbalance & Pipeline Settlement",
  "shortTitle": "Natural Gas Imbalance and Pipeline Settlement",
  "tagline": "Quantify, recover, and prevent financial leakage through natural gas imbalance & pipeline settlement",
  "industry": "Natural Gas Commercial Operations",
  "uiPort": 4623,
  "apiPort": 5623,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Natural Gas Imbalance & Pipeline Settlement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedSettlement",
    "expectedKey": "expectedSettlement",
    "actualLabel": "Received Pipeline Settlement",
    "expectedLabel": "Calculated Settlement Value",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Natural Gas Imbalance & Pipeline Settlement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("pipeline-tariff-library","NGI01","Pipeline tariff library","Execute pipeline tariff library using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed pipeline tariff library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Pipeline tariff library Reference","text","NGI01-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("contract-point-registry","NGI02","Contract point registry","Execute contract point registry using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed contract point registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Contract point registry Reference","text","NGI02-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("nomination-ingestion","NGI03","Nomination ingestion","Execute nomination ingestion using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed nomination ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Nomination ingestion Reference","text","NGI03-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("scheduled-quantity-tracking","NGI04","Scheduled quantity tracking","Execute scheduled quantity tracking using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed scheduled quantity tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Scheduled quantity tracking Reference","text","NGI04-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("meter-allocation-ingestion","NGI05","Meter allocation ingestion","Execute meter allocation ingestion using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed meter allocation ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Meter allocation ingestion Reference","text","NGI05-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("balancing-agreement-control","NGI06","Balancing agreement control","Execute balancing agreement control using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed balancing agreement control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Balancing agreement control Reference","text","NGI06-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("daily-imbalance-calculation","NGI07","Daily imbalance calculation","Execute daily imbalance calculation using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed daily imbalance calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Daily imbalance calculation Reference","text","NGI07-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("cash-out-price-validation","NGI08","Cash-out price validation","Execute cash-out price validation using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed cash-out price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Cash-out price validation Reference","text","NGI08-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("fuel-loss-calculation","NGI09","Fuel loss calculation","Execute fuel loss calculation using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed fuel loss calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Fuel loss calculation Reference","text","NGI09-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("transport-fee-audit","NGI10","Transport fee audit","Execute transport fee audit using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed transport fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Transport fee audit Reference","text","NGI10-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("storage-fee-audit","NGI11","Storage fee audit","Execute storage fee audit using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed storage fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Storage fee audit Reference","text","NGI11-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("penalty-validation","NGI12","Penalty validation","Execute penalty validation using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed penalty validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Penalty validation Reference","text","NGI12-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("pipeline-statement-reconciliation","NGI13","Pipeline statement reconciliation","Execute pipeline statement reconciliation using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed pipeline statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Pipeline statement reconciliation Reference","text","NGI13-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("dispute-workflow","NGI14","Dispute workflow","Execute dispute workflow using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Dispute workflow Reference","text","NGI14-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]}),
feature("point-pipeline-analytics","NGI15","Point pipeline analytics","Execute point pipeline analytics using pipeline tariffs, contracts, points, nominations, schedules, meters, allocations, balancing agreements, cash-out prices, fuel, transport, storage, penalties, statements, and payments.","Produce a governed point pipeline analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pipeline / Contract Point","text","Pipeline / Contract Point · Standard Case"],["caseReference","Point pipeline analytics Reference","text","NGI15-2026-001"],["receivedSettlement","Received Pipeline Settlement","currency",1012000],["expectedSettlement","Calculated Settlement Value","currency",1194160],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Pipeline tariff library case","Contract point registry case","Nomination ingestion case","Scheduled quantity tracking case","Meter allocation ingestion case"]})
]);
